- e2e-tests/experiments/functional/lvm-volume-resize/README.md
- e2e-tests/experiments/functional/lvm-volume-resize/run_e2e_test.yml
- e2e-tests/experiments/functional/lvm-volume-resize/test.yml
- e2e-tests/experiments/functional/lvm-volume-resize/test_vars.yml
- This PR adds e2e-test for lvm-localpv volume resize support.
- Test details can be read from README file.
> feat(e2e-test): Add e2e-test for lvm volume resize support

- README.md
- docs/snapshot.md
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
- add snapshot related docs to LVM LocalPV
No
**Checklist:**
> doc(snapshot): add snapshot doc for LVM

- README.md
- docs/raw-block-volume.md
- docs/resize.md
> chore(doc): adding provisioning/deprovisioning, resize and raw block doc

- pkg/lvm/lvm_util.go
Sometimes `vgs` returns stale information about current free space or currently available logical volumes. It may effect scheduling constructs added as part of GetCapacity implementation.
Reloads lvm metadata cache before list volume groups.
No
NA
**Any additional information for your reviewer?** 
NA
**Checklist:**
> fix(scheduling): reload lvmetad cache before querying volume groups

- deploy/lvm-operator.yaml
- deploy/yamls/lvmnode-crd.yaml
- deploy/yamls/lvmsnapshot-crd.yaml
- deploy/yamls/lvmvolume-crd.yaml
- pkg/apis/openebs.io/lvm/v1alpha1/lvmvolume.go
- pkg/builder/volbuilder/volume.go
- pkg/driver/controller.go
- pkg/driver/params.go
- pkg/lvm/lvm_util.go
Adds support for thin provision lvm volumes. To create a thin provisioned volumes,  following tasks needs to be performed:
- Create a volume group with the vgcreate command.
- Create a thin pool with the lvcreate command.
- Create a thin volume in the thin pool with the lvcreate command.
No
- Thin Provision needs to be enable via StorageClass, for example
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: openebs-lvmsc
allowVolumeExpansion: true
parameters:
volgroup: "lvmvg"
thinprovision: "yes"
provisioner: local.csi.openebs.io
```
- Created one thin …
> feat(provision): add support for thin provision lvm volumes

- README.md
- docs/faq.md
- docs/storageclasses.md
- add docs for custom node labels in storage class
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
> doc(storageclass): add docs for custom node labels

- CHANGELOG.md
- changelogs/released/v0.4.0-RC1/30-prateekpandey14
- changelogs/released/v0.4.0-RC1/37-iyashu
- changelogs/released/v0.4.0-RC1/38-iyashu
- changelogs/released/v0.4.0-RC1/40-shubham14bajpai
Signed-off-by: pawan <pawanprakash101@gmail.com>
> chore(changelog): adding v0.4.0 changelog

- README.md
- docs/storageclasses.md
- Update readme with minimum required k8s version
- Update storage class parameters
> chore(readme): Update readme with minimum required k8s version

- README.md
> chore(doc): update project status to beta

- pkg/lvm/iolimiter.go
- pkg/lvm/iolimiter_test.go
https://github.com/openebs/lvm-localpv/issues/60
**Checklist:**
**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**
The PR title message must follow convention:
`<type>(<scope>): <subject>`.
Where: <br />
- `type` is defining if release will be triggering after merging submitted changes, details in [CONTRIBUTING.md](../CONTRIBUTING.md).
Most common types are:
- `feat`      - for new features, not a …
> corrected prefix match for volgroup names for iops

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
The build.yml and pull_request.yml workflows will ignore pushes made to `docs/` and `changelogs/` directories, all `.md` files, BUILDMETA, LICENSE and MAINTAINERS files.
Added criteria to ignore build workflows on release.
Added Build & Push via Actions jobs instead of makefile.
> chore(github-action): Refine GitHub Actions criteria and perform Build & Push via Actions

- .github/workflows/pull_request.yml
- pkg/lvm/lvm_util.go
- tests/pv/buildlist.go
- tests/pv/persistentvolume.go
**What  PR does ?** 
- fix go var name lint errors
- add golint in lint github action workflow
**Checklist:**
> fix(lints): fix go var name lint errors and add golint in lint workflow

- e2e-tests/apps/busybox/deployers/busybox_statefulset.yml
- e2e-tests/experiments/chaos/app_pod_failure/README.md
- e2e-tests/experiments/functional/lvm-controller-high-availability/README.md
- e2e-tests/experiments/functional/lvm-controller-high-availability/busybox_app.yml
- e2e-tests/experiments/functional/lvm-volume-resize/README.md
- e2e-tests/experiments/functional/lvmpv-custom-topology/README.md
- e2e-tests/experiments/functional/lvmpv-custom-topology/app_gen_immediate.sh
- e2e-tests/experiments/functional/lvmpv-custom-topology/app_gen_wfc.sh
- e2e-tests/experiments/functional/lvmpv-custom-topology/busybox.j2
- e2e-tests/experiments/functional/lvmpv-custom-topology/run_e2e_test.yml
- e2e-tests/experiments/functional/lvmpv-custom-topology/storage_class.j2
- e2e-tests/experiments/functional/lvmpv-custom-topology/test.yml
- e2e-tests/experiments/functional/lvmpv-custom-topology/test_vars.yml
- e2e-tests/experiments/functional/lvmpv-shared-mount/README.md
- e2e-tests/experiments/functional/lvmpv-shared-mount/busybox_share.j2
- e2e-tests/experiments/functional/lvmpv-shared-mount/run_e2e_test.yml
- e2e-tests/experiments/functional/lvmpv-shared-mount/storage_class_shared.j2
- e2e-tests/experiments/functional/lvmpv-shared-mount/test.yml
- e2e-tests/experiments/functional/lvmpv-shared-mount/test_vars.yml
- e2e-tests/experiments/functional/lvmpv-snapshot/README.md
- e2e-tests/experiments/functional/lvmpv-snapshot/run_e2e_test.yml
- e2e-tests/experiments/functional/lvmpv-snapshot/test.yml
- e2e-tests/experiments/functional/lvmpv-snapshot/test_vars.yml
- e2e-tests/experiments/functional/lvmpv-snapshot/volume_snapshot.j2
- e2e-tests/experiments/functional/lvmpv-snapshot/volume_snapshot_class.j2
- e2e-tests/experiments/infra-chaos/node_power_failure/README.md
- e2e-tests/experiments/infra-chaos/service_failure/README.md
- e2e-tests/experiments/lvm-localpv-provisioner/README.md
- e2e-tests/experiments/lvm-localpv-provisioner/test.yml
- e2e-tests/experiments/lvm-localpv-provisioner/volume_snapshot_class.yml
Signed-off-by: w3aman <aman.gupta@mayadata.io
- This PR add e2e-tests for lvm-localpv custom-topology support and share-mount volume
> feat(e2e-test): Add e2e-test for custom-topology and share-mount volume

- docs/storageclasses.md
Signed-off-by: ashishjain <ashish.jain@mayadata.io>
-  Fixing Typo in storage class yaml
- Changed In storageclass volumegroup to volgroup
**Checklist:**
**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**
The PR title message must follow convention:
`<type>(<scope>): <subject>`.
Where: <br />
- `type` is defining if release will be triggering after merging submitted changes, details in …
> Fix typo StorageClass parameters

- CONTRIBUTING.md
- README.md
- docs/developer-setup.md
- docs/storageclasses.md
> chore(doc): adding docs for lvm-localpv

- e2e-tests/experiments/functional/lvmpv-custom-topology/test_vars.yml
- fixed the e2e-test name for lvm custom-topology test
> fix(e2e-test-name): fixed the lvmpv-custom-topology e2e-test name

- pkg/lvm/lvm_util.go
This is required to remove the filesystem headers on lvm volume
before destroying the lvm volume and it is required to fix #80 
This PR wipes the filesystem on lvm volume before destroying
lvm volume.
No
- Provisioned the lvm volume and application.
- Deprovisioned the application and volume and observed the logs of
openebs-lvm-node pod and it says filesystem has been wiped.
- This PR removes the filesystem on lvm volume irrespective whether filesystem …
> fix(volume deletion): wipe the filesystem while destroying lvm volume

- docs/persistentvolumeclaim.md
- docs/storageclasses.md
This PR is required to show the conformance matrix of available options in PVC & SC.
This PR add following changes in documents:
- Add conformance matrix for PVC & SC options.
- Add an example YAMLs of the above options.
No
Not Applicable
**Checklist:**
> chore(doc): add Conformance matrix for PVC & SC spec

- docs/persistentvolumeclaim.md
- docs/storageclasses.md
This enhances the representation structure of the PVC & SC conformance matrix.
This PR updates the representation structure of the PVC & SC Confirmance matrix.
No
**Checklist:**
> chore(doc): update conformance matrix of SC & PVC

- docs/thin_provision.md
Add docs and command to enable the monitoring on thin pools to use the auto extend feature of lvm volumes.
**Checklist:**
> chore(docs): auto-extend LVM thin pools configuration docs

- docs/csi_capability.md
Add CSI controller and node driver capabilities and their status (implemented or not implemented) and description.
> chore(doc): add conformance matrix of csi capabilities

- README.md
- Update readme with lvm driver installation step from charts repo.
> chore(readme): Update readme with lvm driver installation from charts repo

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
Update local pv helm chart to v0.6.0 version.
NO
**Checklist:**
> [stable/lvm]: update helm charts to 0.6.0 release

- design/lvm/resize_workflow.md
This PR adds additional test scenarios to verify volume
expansion feature.
No
NA
**Checklist:**
> chore(doc): add test scenarios to verify volume expansion workflow

- e2e-tests/experiments/upgrade-lvm-localpv/README.md
- e2e-tests/experiments/upgrade-lvm-localpv/run_e2e_test.yml
- e2e-tests/experiments/upgrade-lvm-localpv/test.yml
- e2e-tests/experiments/upgrade-lvm-localpv/test_vars.yml
- This PR adds automation for lvm-localpv upgrade.
> add(e2e-test): add automation test-case for lvm-localpv driver upgrade

- docs/snapshot.md
Add `snapSize` snapshotclass parameter docs
> chore(docs): add snapSize snapshotclass parameter docs

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
update LVM charts to release 0.7.0 version
> [stable/lvm]: update lvm charts to release 0.7.0

- tests/provision_test.go
- tests/suite_test.go
- tests/utils.go
An integration test for csi volume volume leak protection added in https://github.com/openebs/lvm-localpv/pull/76
No
**Checklist:**
> test(bdd): add integration test for pvc leak protection

- Adopters.md
- upgrade/README.md
- This PR adds adopters list and upgrade steps for lvm-localpv
> chore(doc): Added upgrade doc and adopters list for lvm-localpv

- e2e-tests/hack/crds.yaml
- e2e-tests/hack/rbac.yaml
- Update e2e-crds apiversion to v1
> refact(e2e-crd): update lvm e2e-crds apiversion to v1

- e2e-tests/hack/e2e-result.j2
- fix typo in kind filed of e2e-result yaml file
> fix(typo): fix typo in kind field of E2e-result cr yaml file

- design/lvm/persistent-volume-claim/access_mode.md
- design/lvm/persistent-volume-claim/capacity_resource.md
- design/lvm/persistent-volume-claim/selector.md
- design/lvm/persistent-volume-claim/storage_class.md
- design/lvm/persistent-volume-claim/volume_mode.md
- design/lvm/persistent-volume-claim/volume_name.md
- design/lvm/resize_workflow.md
- design/lvm/storageclass-parameters/allowed_topologies.md
- design/lvm/storageclass-parameters/fs_type.md
- design/lvm/storageclass-parameters/mount_options.md
- design/lvm/storageclass-parameters/reclaim_policy.md
- design/lvm/storageclass-parameters/shared.md
- design/lvm/storageclass-parameters/thin_provision.md
- design/lvm/storageclass-parameters/vg_pattern.md
- design/lvm/storageclass-parameters/volume_binding_mode.md
- docs/persistentvolumeclaim.md
- docs/storageclasses.md
This PR adds workflows for various parameters of PVC and SC
No
**Checklist:**
> chore(design): design workflow for PVC and SC options

- README.md
> chore(doc): using same volgroup name in the doc

- deploy/lvm-operator.yaml
- deploy/yamls/lvm-driver.yaml
update zfs operator with custom priorityclass
No
Refer: #125
**Checklist:**
> refact(operator): update lvm operator with custom priorityclass

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
- update helm charts to 0.8.0 release
- fix the duplicate label in pod labels #131
> [stable/lvm]: update lvm localpv charts to 0.8.0 release

- README.md
> chore(doc): updating project status

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/lvm-controller.yaml
- deploy/helm/charts/templates/lvm-node.yaml
fixes the helm templates of CSI driver controller and node to include the custom priorityclass changes
> fix(templates): update csi driver templates with priorityclass

- e2e-tests/experiments/functional/lvmpv-raw-block-volume/README.md
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/busybox.j2
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/run_e2e_test.yml
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/test.yml
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/test_vars.yml
- e2e-tests/experiments/lvm-localpv-provisioner/openebs-lvmsc.j2
- This PR adds e2e-test for raw block volume for lvm-localpv
> feat(e2e): add e2e-test for raw block volume for lvm-localpv

- README.md
- deploy/lvm-operator.yaml
- deploy/yamls/lvm-driver.yaml
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/README.md
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/busybox.j2
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/run_e2e_test.yml
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/test.yml
- e2e-tests/experiments/functional/lvmpv-raw-block-volume/test_vars.yml
- e2e-tests/experiments/lvm-localpv-provisioner/openebs-lvmsc.j2
- upgrade/README.md
This PR is cherry-pick of commits of following PR
- #132 
- #142 
- #143 
This PR cherry-picks required commits from the master branch for new release.
No
**Checklist:**
> chore(cherry-pick): cherry-pick of #132, #142 & #143

- .github/workflows/build.yml
- .github/workflows/release.yml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
This adds Github Actions CI instructions to push built images to GHCR image registry.
Adds GHCR login and registry prefix to images.
> chore(ci): add GHCR build and push steps to build.yml and release.yml

- e2e-tests/experiments/upgrade-lvm-localpv/test.yml
> chore(cherry-pick): Cherry-pick for PR #148 into v0.8.x

- .github/workflows/build.yml
- .github/workflows/release.yml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
This cherry-picks the following into v0.8.x branch:
1. #150
> Cherry-pick #150

- .github/workflows/build.yml
- .github/workflows/chart-lint-test.yml
- .github/workflows/pull_request.yml
- .github/workflows/release-charts.yml
- CONTRIBUTING.md
- GOVERNANCE.md
- buildscripts/push
- ct.yaml
- docs/developer-setup.md
- docs/persistentvolumeclaim.md
- docs/snapshot.md
- docs/storageclasses.md
- e2e-tests/experiments/lvm-localpv-provisioner/README.md
- e2e-tests/experiments/lvm-localpv-provisioner/run_e2e_test.yml
- e2e-tests/experiments/upgrade-lvm-localpv/README.md
This PR requires to mark develop as the default branch
This PR does the following changes:
- Updates branch reference from master to develop(HEAD) in README.md files
- Updates build branch to 'develop' in github workflow
No
**Checklist:**
> chore(ci): updating branch reference from master to develop(HEAD)

- .github/workflows/build.yml
- .github/workflows/chart-lint-test.yml
- .github/workflows/pull_request.yml
- .github/workflows/release-charts.yml
- CONTRIBUTING.md
- GOVERNANCE.md
- buildscripts/push
- ct.yaml
- docs/developer-setup.md
- docs/persistentvolumeclaim.md
- docs/snapshot.md
- docs/storageclasses.md
- e2e-tests/experiments/lvm-localpv-provisioner/README.md
- e2e-tests/experiments/lvm-localpv-provisioner/run_e2e_test.yml
- e2e-tests/experiments/upgrade-lvm-localpv/README.md
> chore(ci): updating branch reference from master to develop(HEAD) (#152)
