openebs/lvm-localpv

.github/workflows/pull_request.yml
buildscripts/lvm-driver/Dockerfile
changelog/unreleased/1-pawanpraka1
changelog/unreleased/2-pawanpraka1
deploy/lvm-operator.yaml
deploy/yamls/lvm-driver.yaml
pkg/driver/agent.go
pkg/driver/controller.go
pkg/lvm/lvm_util.go
pkg/lvm/volume.go

fixes: https://github.com/openebs/lvm-localpv/issues/3
adding resize support for lvm volumes
**Checklist:**

feat(resize): adding resize support for lvm volumes

---

changelogs/unreleased/14-pawanpraka1
deploy/sample/fio-block.yaml
pkg/driver/agent.go
pkg/lvm/lvm_util.go
pkg/lvm/mount.go

adding raw block volume support for LVM
No
tested with the sample fio yaml added in this PR

feat(block): adding raw block volume support for LVM

---

pkg/lvm/lvm_util.go

fix(localpv): ensure lvm volume creation & deletion idempotent

---

Makefile
deploy/lvm-operator.yaml
deploy/yamls/lvm-driver.yaml
deploy/yamls/lvmnode-crd.yaml
deploy/yamls/lvmsnapshot-crd.yaml
deploy/yamls/lvmvolume-crd.yaml

Signed-off-by: shubham <shubham.bajpai@mayadata.io>
With k8s v1.22 the v1beta1 for various resources will no longer be supported. This PR updates the storage and apiexention version to v1.
**Does this PR require any upgrade changes?**: No
**Checklist:**

chore(k8s): updated storage and apiextension version to v1

---

buildscripts/lvm-driver/Dockerfile.buildx

Fix: #53 
- Add missing xfs package `xfsprogs-extra` in .buildx file

fix(dockerfile): Add missing xfs package in .buildx file

---

changelogs/unreleased/55-akhilerm
pkg/driver/controller.go
pkg/lvm/lvm_util.go
pkg/mgmt/snapshot/snapshot.go
tests/provision_test.go
tests/pv/build.go
tests/pv/buildlist.go
tests/pv/kubernetes.go
tests/pv/persistentvolume.go
tests/suite_test.go
tests/utils.go

When an LVM volume  with active snapshot is deleted, both volume and snapshot is removed from the machine, but the resources corresponding to the snapshot still exists in the cluster. This stale snapshot resources will cause the controller to error out when we try to delete these resources as the actual snapshot does not exist.
- error out the DeleteVolume() controller gRPC call if the volume has active snapshots
No
**Checklist:**

fix(provision): prevent volume deletion if snapshot exists

---

README.md
ci/ci-test.sh
docs/thin_provision.md
pkg/lvm/iolimiter_test.go
pkg/lvm/lvm_util.go
pkg/mgmt/volume/volume.go
tests/provision_test.go
tests/utils.go

Handle the thin pool creation which can not be greater or equal to volumegroup size.
Earlier PV size has been used while thin pool creation, which throws insufficient space error in case if thin volume
size greater or equal then the actual volumegroup size.
As part of this change we are using the half of volumegroup size to make it lesser while creating thin pool.
NO
**Checklist:**

fix(thin): use volume group size to create thin pool

---

pkg/driver/agent.go
pkg/lvm/mount.go

This PR is required to pass underlying mount errors to application as pod events.
This PR returns the root cause of mount issue along with the status code for gRPC request.
No
- Deploying application with invalid mount options
_Events on pod without changes:_
```sh
Events:
Type     Reason       Age               From                      Message
----     ------       ----              ----                      -------
Normal   Scheduled    39s               default-scheduler         Successfully assigned default/fio to centos-worker-1
Warning  FailedMount  7s (x7 over 39s) …
```

chore(mount): propagate mount errors to application pod events

---

.github/workflows/chart-lint-test.yml
buildscripts/kind_config.yaml
deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/values.yaml

Bump lvm localpv charts to 0.5.0 
**Checklist:**

[stable/lvm]: update helm charts to 0.5.0 release

---

.github/workflows/build.yml
.golangci.yml
Makefile
pkg/driver/agent.go
pkg/driver/controller.go
pkg/driver/driver.go
pkg/driver/grpc.go
pkg/lvm/iolimiter.go
pkg/lvm/lvm_util.go
pkg/lvm/mount.go
pkg/mgmt/lvmnode/lvmnode.go
pkg/usage/usage.go
pkg/usage/versionset.go

This PR is required to make static analysis of the codebase and
it is achieved by adding lint tool in the codebase.
This PR adds [golangci-lint](https://golangci-lint.run/usage/configuration/) tool to verify linting issues in the codebase
No
Yes
- Currently, disabled `structcheck` analysis due to some [false-positive](https://github.com/golangci/golangci-lint/issues/537) errors and it can be enabled once the issue was resolved.
- Disabled linter on test …

chore(linter): add golangci-lint tool for checking the gocode base

---

pkg/driver/controller.go

This PR is required to restrict the creation of volume with
ReadWriteMany & ReadOnlyMany access modes.
ReadWriteMany: volume can be mounted in read/write mode to many hosts.
ReadOnlyMany: volume can be mounted in readonly mode to many hosts.
ReadWriteOnce: volume can be mounted in read/write mode to one host.
This PR adds validation to validate the create volume
request(gRPC) access mode. It supports only a single node writer
i.e `ReadWriteOnce` access mode and will return an error for
other modes like `ReadWriteMany` & `ReadOnlyMany`
No
- Provisioned a PVC with RWX access mode …

fix(create): validate create volume request access mode

---

pkg/driver/controller.go
pkg/mgmt/csipv/leak_protection.go

Here is the sequence of events that can produce a volume leak:
1. create a new pvc with late binding.
2. provision the volume in your csi driver `CreateVolume` as usual, but return artificial unsuccessful response (non-ok grpc code) to the csi external provisioner even though you are able to successfully provisioned the volume.
3. delete the pvc that you created earlier and wait for it till it gets completely removed.
4. terminate the csi controller plugin pod.
5. even after restarting the csi controller plugin pod, you'll see that underlying volume (lvm volume resource in our case) still exists without any pvc or pv associated with it thus leaking the underlying storage infra structure.
It is a known limitation of csi spec itself …

fix(prov): add controller to avoid potential volume leaks

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/templates/lvm-controller.yaml
deploy/lvm-operator.yaml
deploy/yamls/lvm-driver.yaml

Set default fstype to ext4 in csi-provisioner. This will be helpful when fsType is not mention in storageclass.

feat(charts): set default fstype to ext4 in csi-provisioner

---

pkg/driver/controller.go
pkg/lvm/volume.go

Signed-off-by: Abhinandan-Purkait <abhinandan.purkait@mayadata.io>
- LocalPV LVM currently doesnot have any cas-type label to indicate its cas-type.
- This PR adds the cas-type label to the volume attributes. 
**Checklist:**

Add missing cas-type key for lvm under volume attributes

---

pkg/lvm/lvm_util.go

This PR is required to wipe existing filesystem signatures before creating LVM volume.
This PR wipes the filesystem signatures during LVM volume
creation time. "-y" option is used not to prompt for confirmation
interactively but always assume the answer yes(Answering yes will
wipe the previous filesystem signatures)
No
**Checklist:**

fix(create): wipe the filesystem signatures during LVM volume creation

---

pkg/driver/controller.go
pkg/driver/params.go
pkg/lvm/lvm_util.go

To support thin snapshot for lvm volumes
Add support for thin snapshot for lvm volumes based on the SnapSize configured in SnapshotClass.
So there are two scenarios here :
**1. Snapshot class `snapsize` parameter.**
In this case whether volume is thin provisioned or thick provisioned, we should create a thick snapshot with size as `snapsize` mentioned in the snapshotclass.
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
name: lvmpv-snapclass
annotations:
snapshot.storage.kubernetes.io/is-default-class: "true"
parameters:
snapsize: 1Gi
driver: local.csi.openebs.io
deletionPolicy: Delete
```
```bash
$ sudo lvs
LV …
```

feat(snapshot): add support for thin snapshot for lvm volumes

---

.github/workflows/pull_request.yml
.github/workflows/release.yml

Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This PR addresses the issue where a release workflow is triggered when a helm chart is released. The images pushed have tags with the name of the chart like [`lvm-localpv-0.6.0`](https://github.com/openebs/lvm-localpv/actions/runs/939055836) in this case. We should avoid building images in such cases. The if condition added in the workflow prevents such workflows from executing.
**Checklist:**

fix(actions): skip release workflow on helm release

---

.github/workflows/chart-lint-test.yml
deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/templates/lvm-node-service.yaml
deploy/helm/charts/templates/lvm-node.yaml
deploy/helm/charts/templates/service.yaml
deploy/helm/charts/values.yaml
deploy/lvm-operator.yaml
deploy/yamls/lvm-driver.yaml

**Why is this PR required? What issue does it fix?**
- Pass `listen-address` flag value through arguments.
- This PR is also required for **Service Discovery** in Prometheus.
- To get LVM metrics in Prometheus:
`Metrics Endpoint <- Service <- ServiceMonitor -> Prometheus`
- Add configuration for service yaml which needs to be installed when lvm-metrics collection is enabled.
- LVM metrics endpoint is passed via arguments to openebs-lvm-plugin.
- This PR also adds service yaml while installing lvm-localPV via helm chart.
- Configuration in values.yaml:
```
lvmPlugin:
...
metricsPort: 9500
...
```
- If **metricsPort** is set, then this value is passed through the environment variable to openebs-lvm-plugin which is used in the code as an endpoint to expose LVM metrics …

fix(helm): Pass listen-address flag through arguments and install service.

---

e2e-tests/experiments/functional/lvmpv-custom-topology/test.yml

- This PR refactors the custom-topology e2e-test with respect to the latest changes done in this PR https://github.com/openebs/lvm-localpv/pull/110
- Now we have to set the ALLOWED_TOPOLOGIES in the daemonset spec env's in openebs-lvm-plugin container,
```
env:
- name: OPENEBS_NODE_ID
valueFrom:
fieldRef:
fieldPath: spec.nodeName
- name: OPENEBS_CSI_ENDPOINT
value: unix:///plugin/csi.sock
- name: OPENEBS_NODE_DRIVER
value: agent
- name: LVM_NAMESPACE
value: openebs
- name: ALLOWED_TOPOLOGIES
value: "openebs.io/rack"
```

refact(e2e): refactor the custom-topology e2e-test

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/templates/lvm-node.yaml
deploy/helm/charts/values.yaml

Add allowed topologies ENV in node daemonset template
```
$  helm install openebs --dry-run --namespace openebs .
```
```yaml
env:
- name: OPENEBS_NODE_ID
valueFrom:
fieldRef:
fieldPath: spec.nodeName
- name: OPENEBS_CSI_ENDPOINT
value: unix:///plugin/csi.sock
- name: OPENEBS_NODE_DRIVER
value: agent
- name: LVM_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: METRICS_LISTEN_ADDRESS
value: :9500
- name: ALLOWED_TOPOLOGIES
value: kubernetes.io/hostname,
```

[stable/lvm]: add allowed topologies env in node daemonset

---

e2e-tests/chaoslib/service_failure/service_chaos.yml

- For docker-restart test-case if we try to stop docker services on node with the command something like: 
` systemctl stop docker.service`
it can give such warning
```
Warning: Stopping docker.service, but it can still be activated by:
docker.socket
```
And then docker services will still be running.
So we can stop docker via socket and can execute following command:
` systemctl stop docker.socket`

refact(e2e): refactor the infra-chaos service-failure e2e-test

---

deploy/lvm-operator.yaml
deploy/yamls/lvm-driver.yaml

Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>
The lvm-node service were not be to discover/identify the endpoints because of being installed in different ns  then the lvm node daemonset through operator.
This PR adds namespace field in the metadata section to the service same as the namespace in which the lvm-node/lvm-driver daemonset is installed to that the service is able to successfully identify its endpoints.
No.
**Checklist:**

fix(endpoints-discovery): Fixed lvm-node svc endpoints discovery

---

deploy/lvm-operator.yaml
deploy/yamls/lvm-driver.yaml
upgrade/README.md

Update the CSI driver sidecars version as below:
- CSI Provisioner: 
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
- CSI Resizer:
k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
- CSI Node Driver Registrar
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0

Update(deploy): Update the k8s csi sidecar versions

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/templates/lvm-controller.yaml
deploy/helm/charts/values.yaml

This PR updates the K8s sidecar images in helm installation
Please refer to #137 
This PR does the following changes:
- Update the CSI driver sidecars version as below:
CSI Provisioner:
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
CSI Resizer:
k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
CSI Node Driver Registrar
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
No
Yes, by provisioning volume with changes.
**Checklist:**
Signed-off-by: mittachaitu …

chore(CSI Images): Update helm k8s csi sidecar versions

---

README.md

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
Fixes the Slack badge link to point to the Kubernetes slack workspace's #openebs channel.

chore(README): fix Slack badge link

---

e2e-tests/experiments/upgrade-lvm-localpv/test.yml

- Due to Change in CSI_driver spec, we need to delete csi-driver CR before apply the updated operator yaml, otherwise csi-driver will no get updated as of immutable spec fields. 
```
The CSIDriver "local.csi.openebs.io" is invalid: spec.storageCapacity: Invalid value: true: field is immutable
```

refact(e2e): Cleanup csi-driver CR before applying updated operator yaml

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/templates/lvm-controller.yaml
deploy/helm/charts/templates/lvm-node.yaml
deploy/helm/charts/values.yaml

- allows to optionally reduce log noise
- reduces load on controllers / etcd for single replica deployments
Disable leader-election for the controllers if replicas = 1
No.

feat(helm): Disable leader-elections if replicas=1, make logLevel configurable
